# name: ${HOST_USERNAME}-web-ui-compose

# services:
#   web-ui:
#     build:
#       context: ..
#       dockerfile: web/Dockerfile
#     container_name: ${HOST_USERNAME}-web-ui-container
#     image: g6-web-ui:latest

#     # ports:
#     #   - "127.0.0.1:${WEB_PORT}:${WEB_CONTAINER_PORT}"

#     # environment:
#     #   - WEB_PORT=${WEB_CONTAINER_PORT}
#     #   - REPO_DIR=/home/root
#     #   - API_PORT_FILE=/home/root/api/ngrok-port
#     #   - SSH_USER=${SSH_USER:-}
#     #   - SSH_HOST=${SSH_HOST:-}
#     #   - LOCAL_PORT=${LOCAL_PORT:-5173}

#     ports:
#       - "127.0.0.1:${WEB_PORT}:${WEB_CONTAINER_PORT}"

#     extra_hosts:
#     - "host.docker.internal:host-gateway"

#     environment:
#       - LISTEN_PORT=${WEB_CONTAINER_PORT}
#       - PUBLISHED_PORT=${WEB_PORT}
#       - REPO_DIR=/home/root
#       - API_PORT_FILE=/home/root/api/ngrok-port

#     working_dir: /home/root

#     volumes:
#       - ${REPO_PATH}/web:/home/root/web
#       # - ${REPO_PATH}/api:/home/root/api:ro
#       - ${REPO_PATH}/api/ngrok-port:/home/root/api/ngrok-port:ro

#     stdin_open: true
#     tty: true
#     command: bash
#     network_mode: bridge
#     restart: unless-stopped








# web/docker-compose.yaml
name: ${HOST_USERNAME}-web-ui-compose

services:
  web-ui:
    build:
      context: ..
      dockerfile: web/Dockerfile
    container_name: ${HOST_USERNAME}-web-ui-container
    image: g6-web-ui:latest

    ports:
      - "127.0.0.1:${WEB_PORT}:${WEB_CONTAINER_PORT}"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - LISTEN_PORT=${WEB_CONTAINER_PORT}
      - PUBLISHED_PORT=${WEB_PORT}
      - REPO_DIR=/home/root
      - API_URL_FILE=/home/root/api/ngrok-url

    working_dir: /home/root

    volumes:
      - ${REPO_PATH}/web:/home/root/web
      - ${REPO_PATH}/api/ngrok-url:/home/root/api/ngrok-url:ro

    stdin_open: true
    tty: true
    command: bash
    network_mode: bridge
    restart: unless-stopped
